stakater-db:
 image: mysql:latest
 container_name: stakater-db
 net: "container:stakater_app"
 volumes:
 - /home/stakater-db-data:/var/lib/mysql
 environment:
 - MYSQL_ROOT_PASSWORD=123456

stakater_app:
 image: localhost:5000/stakater:latest
 container_name: stakater-app
 ports:
   - "app-public-ip:8080"
   - "3306:3306"
