mysql-db:
 image: mysql:latest
 container_name: mysql-db
 net: "container:sample-app"
 volumes:
 - /home/stakater-db-data:/var/lib/mysql
 environment:
 - MYSQL_ROOT_PASSWORD=123456

sample-app:
 image: localhost:5000/stakater:latest
 container_name: sample-app
 ports:
   - "app-public-port:8080"
   - "3306:3306"
